"""
JSON Fusion (Step 04)
Integrates the layout bounding boxes (Step 02) with recognized text (Step 03)
into a single, structured digital document representation.
"""

import json
from pathlib import Path
import argparse

def fuse_document(layout_json_path: str, trocr_json_path: str, output_path: str):
    layout_file = Path(layout_json_path).resolve()
    trocr_file = Path(trocr_json_path).resolve()
    out_file = Path(output_path).resolve()
    
    if not layout_file.exists():
        print(f"Error: Layout JSON not found at {layout_file}")
        return
    if not trocr_file.exists():
        print(f"Error: TrOCR Results JSON not found at {trocr_file}")
        return
        
    with open(layout_file, 'r', encoding='utf-8') as f:
        layout_data = json.load(f)
        
    with open(trocr_file, 'r', encoding='utf-8') as f:
        trocr_data = json.load(f)
        
    fused_regions = []
    
    for region in layout_data.get("regions", []):
        order = region["reading_order"]
        # Match crop filename generated by export_rois.py (e.g., 1_1_region_001.jpg)
        doc_name = layout_data.get("document_name", "doc")
        crop_filename = f"{doc_name}_region_{order:03d}.jpg"
        
        recognized_text = trocr_data.get(crop_filename, "")
        
        fused_region = {
            "reading_order": order,
            "class_name": region["class_name"],
            "bbox": region["bbox"],
            "confidence_layout": region["confidence"],
            "text": recognized_text
        }
        fused_regions.append(fused_region)
        
    fused_document = {
        "document_name": layout_data.get("document_name"),
        "page_dimensions": layout_data.get("page_dimensions"),
        "total_regions": layout_data.get("total_regions"),
        "regions": fused_regions
    }
    
    out_file.parent.mkdir(parents=True, exist_ok=True)
    with open(out_file, 'w', encoding='utf-8') as f:
        json.dump(fused_document, f, indent=2, ensure_ascii=False)
        
    print(f"Successfully fused layout and text into: {out_file}")
    
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Fuse Layout and TrOCR JSON outputs")
    parser.add_argument("--layout", type=str, required=True, help="Path to Step 2 layout JSON")
    parser.add_argument("--trocr", type=str, required=True, help="Path to Step 3 TrOCR results JSON")
    parser.add_argument("--output", type=str, required=True, help="Path to save fused JSON")
    args = parser.parse_args()
    
    fuse_document(args.layout, args.trocr, args.output)
